apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-prometheus-community.yaml
  - helm-cloudflare.yaml
  - helm-openvpn.yaml
  - helm-grafana.yaml
  - helm-bitnami.yaml
