---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    toolkit.fluxcd.io/tenant: apps
